# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ana.ui'
#
# Created: Sun Dec 17 21:14:24 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1355, 940)
        self.groupBox_26 = QtGui.QGroupBox(Dialog)
        self.groupBox_26.setGeometry(QtCore.QRect(0, 10, 1311, 921))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_26.setFont(font)
        self.groupBox_26.setObjectName(_fromUtf8("groupBox_26"))
        self.table = QtGui.QTableWidget(self.groupBox_26)
        self.table.setGeometry(QtCore.QRect(20, 30, 961, 271))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        self.table.setFont(font)
        self.table.setObjectName(_fromUtf8("table"))
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.groupBox_27 = QtGui.QGroupBox(self.groupBox_26)
        self.groupBox_27.setGeometry(QtCore.QRect(10, 310, 1281, 601))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_27.setFont(font)
        self.groupBox_27.setObjectName(_fromUtf8("groupBox_27"))
        self.table_0 = QtGui.QTableWidget(self.groupBox_27)
        self.table_0.setGeometry(QtCore.QRect(10, 40, 941, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        self.table_0.setFont(font)
        self.table_0.setObjectName(_fromUtf8("table_0"))
        self.table_0.setColumnCount(0)
        self.table_0.setRowCount(0)
        self.table_1 = QtGui.QTableWidget(self.groupBox_27)
        self.table_1.setGeometry(QtCore.QRect(10, 150, 941, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        self.table_1.setFont(font)
        self.table_1.setObjectName(_fromUtf8("table_1"))
        self.table_1.setColumnCount(0)
        self.table_1.setRowCount(0)
        self.table_3 = QtGui.QTableWidget(self.groupBox_27)
        self.table_3.setGeometry(QtCore.QRect(10, 370, 941, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        self.table_3.setFont(font)
        self.table_3.setObjectName(_fromUtf8("table_3"))
        self.table_3.setColumnCount(0)
        self.table_3.setRowCount(0)
        self.table_2 = QtGui.QTableWidget(self.groupBox_27)
        self.table_2.setGeometry(QtCore.QRect(10, 260, 941, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        self.table_2.setFont(font)
        self.table_2.setObjectName(_fromUtf8("table_2"))
        self.table_2.setColumnCount(0)
        self.table_2.setRowCount(0)
        self.table_4 = QtGui.QTableWidget(self.groupBox_27)
        self.table_4.setGeometry(QtCore.QRect(10, 480, 941, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        self.table_4.setFont(font)
        self.table_4.setObjectName(_fromUtf8("table_4"))
        self.table_4.setColumnCount(0)
        self.table_4.setRowCount(0)
        self.label_2 = QtGui.QLabel(self.groupBox_27)
        self.label_2.setGeometry(QtCore.QRect(960, 40, 101, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_27)
        self.label_3.setGeometry(QtCore.QRect(960, 150, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_27)
        self.label_4.setGeometry(QtCore.QRect(960, 260, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_27)
        self.label_5.setGeometry(QtCore.QRect(960, 370, 101, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_27)
        self.label_6.setGeometry(QtCore.QRect(960, 480, 101, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label = QtGui.QLabel(self.groupBox_26)
        self.label.setGeometry(QtCore.QRect(100, 10, 501, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox = QtGui.QGroupBox(self.groupBox_26)
        self.groupBox.setGeometry(QtCore.QRect(1010, 30, 271, 271))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.btn_bol = QtGui.QPushButton(self.groupBox)
        self.btn_bol.setEnabled(False)
        self.btn_bol.setGeometry(QtCore.QRect(150, 90, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        self.btn_bol.setFont(font)
        self.btn_bol.setObjectName(_fromUtf8("btn_bol"))
        self.btn_basr = QtGui.QPushButton(self.groupBox)
        self.btn_basr.setEnabled(False)
        self.btn_basr.setGeometry(QtCore.QRect(30, 130, 221, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        self.btn_basr.setFont(font)
        self.btn_basr.setObjectName(_fromUtf8("btn_basr"))
        self.btn_veriYukle = QtGui.QPushButton(self.groupBox)
        self.btn_veriYukle.setGeometry(QtCore.QRect(30, 90, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        self.btn_veriYukle.setFont(font)
        self.btn_veriYukle.setObjectName(_fromUtf8("btn_veriYukle"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(40, 180, 211, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox_26.setTitle(_translate("Dialog", "Bütün Kayitlar", None))
        self.groupBox_27.setTitle(_translate("Dialog", "Veri Parçaları", None))
        self.label_2.setText(_translate("Dialog", "Başarısı : ", None))
        self.label_3.setText(_translate("Dialog", "Başarısı : ", None))
        self.label_4.setText(_translate("Dialog", "Başarısı : ", None))
        self.label_5.setText(_translate("Dialog", "Başarısı : ", None))
        self.label_6.setText(_translate("Dialog", "Başarısı : ", None))
        self.label.setText(_translate("Dialog", "Veri Yükleyiniz", None))
        self.groupBox.setTitle(_translate("Dialog", "İşlemler", None))
        self.btn_bol.setText(_translate("Dialog", "Verileri Böl", None))
        self.btn_basr.setText(_translate("Dialog", "Başar Hesapla", None))
        self.btn_veriYukle.setText(_translate("Dialog", "Verileri Yükle", None))
        self.label_13.setText(_translate("Dialog", "Ortalama Başarısı : ", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

